trigger:
  - master

pr:
  - master

stages:
  - stage: Checks
    jobs:
      - job: CodeStyle
        timeoutInMinutes: 5
        pool:
          vmImage: 'ubuntu-latest'
        steps:
          - task: UsePythonVersion@0
            inputs:
              versionSpec: '3.6'
            displayName: 'Use Python 3.6'

          - script: |
              python -m pip install --upgrade pip
              pip install black
              black --check src setup.py tests tools
            displayName: 'black'

      - job: Test
        timeoutInMinutes: 10
        pool:
          vmImage: 'ubuntu-latest'
        strategy:
          matrix:
            Python36:
              python.version: '3.6'
            Python37:
              python.version: '3.7'
        steps:
          - task: UsePythonVersion@0
            inputs:
              versionSpec: '$(python.version)'
            displayName: 'Use Python $(python.version)'

          - script: |
              python -m pip install --upgrade pip
              pip install -r requirements.txt
              pip install pytest-azurepipelines
            displayName: 'Install dependencies'

          - script: |
              pytest tests
            displayName: 'pytest'

  - stage: Build
#    condition: eq(Build.SourceBranch, 'refs/heads/master') #FIXME
    jobs:
      - job: BuildWheel
        timeoutInMinutes: 5
        pool:
          vmImage: 'ubuntu-latest'
        steps:
          - task: UsePythonVersion@0
            inputs:
              versionSpec: '3.6'
            displayName: 'Use Python 3.6'

          - script: |
              python -m pip install --upgrade pip
              pip install -U twine wheel
            displayName: 'Install dependencies'

          - script: |
              python setup.py sdist bdist_wheel
              twine check dist/*
            displayName: 'Build wheel'

          - task: PublishBuildArtifacts@1
            inputs:
              pathtoPublish: dist/
              artifactName: Flying_Circus_Wheel
            displayName: 'Publish Artifacts in Azure'

      - job: Validate
        dependsOn: BuildWheel
        timeoutInMinutes: 5
        pool:
          vmImage: 'ubuntu-latest'
        # FIXME use a strategy matrix here for multiple OS'es in vm
        steps:
          - task: UsePythonVersion@0
            inputs:
              versionSpec: '3.6'
            displayName: 'Use Python 3.6'

          - task: DownloadBuildArtifacts@0
            inputs:
              buildType: 'current'
              downloadType: 'single'
              artifactName: Flying_Circus_Wheel
              itemPattern: '**'
              downloadPath: '$(System.ArtifactsDirectory)'
            displayName: 'Download Artifact'

          - script: |
              python -m pip install --upgrade pip
              ls $(System.ArtifactsDirectory)/Flying_Circus_Wheel/
              find $(System.ArtifactsDirectory)/Flying_Circus_Wheel/*.whl | xargs pip install
              python -c "import flyingcircus; s = flyingcircus.core.Stack(); print(s.export())"
            displayName: 'Validate Wheel'
        # FIXME
        # TODO add post-build install in fresh multi-OS, check install works
