"""Raw representations of every data type in the AWS AppConfig service.

See Also:
    `AWS developer guide for AppConfig
    <https://docs.aws.amazon.com/appconfig/latest/userguide/what-is-appconfig.html>`_

This file is automatically generated, and should not be directly edited.
"""

from attr import attrib
from attr import attrs

from ..core import ATTRSCONFIG
from ..core import Resource
from ..core import ResourceProperties
from ..core import create_object_converter

__all__ = [
    "Application",
    "ApplicationProperties",
    "ConfigurationProfile",
    "ConfigurationProfileProperties",
    "Deployment",
    "DeploymentProperties",
    "DeploymentStrategy",
    "DeploymentStrategyProperties",
    "Environment",
    "EnvironmentProperties",
    "HostedConfigurationVersion",
    "HostedConfigurationVersionProperties",
]


@attrs(**ATTRSCONFIG)
class ApplicationProperties(ResourceProperties):
    Description = attrib(default=None)
    Name = attrib(default=None)
    Tags = attrib(default=None)


@attrs(**ATTRSCONFIG)
class Application(Resource):
    """A Application for AppConfig.

    See Also:
        `AWS Cloud Formation documentation for Application
        <http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-appconfig-application.html>`_
    """

    RESOURCE_TYPE = "AWS::AppConfig::Application"

    Properties: ApplicationProperties = attrib(
        factory=ApplicationProperties,
        converter=create_object_converter(ApplicationProperties),
    )


@attrs(**ATTRSCONFIG)
class ConfigurationProfileProperties(ResourceProperties):
    ApplicationId = attrib(default=None)
    Description = attrib(default=None)
    LocationUri = attrib(default=None)
    Name = attrib(default=None)
    RetrievalRoleArn = attrib(default=None)
    Tags = attrib(default=None)
    Validators = attrib(default=None)


@attrs(**ATTRSCONFIG)
class ConfigurationProfile(Resource):
    """A Configuration Profile for AppConfig.

    See Also:
        `AWS Cloud Formation documentation for ConfigurationProfile
        <http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-appconfig-configurationprofile.html>`_
    """

    RESOURCE_TYPE = "AWS::AppConfig::ConfigurationProfile"

    Properties: ConfigurationProfileProperties = attrib(
        factory=ConfigurationProfileProperties,
        converter=create_object_converter(ConfigurationProfileProperties),
    )


@attrs(**ATTRSCONFIG)
class DeploymentProperties(ResourceProperties):
    ApplicationId = attrib(default=None)
    ConfigurationProfileId = attrib(default=None)
    ConfigurationVersion = attrib(default=None)
    DeploymentStrategyId = attrib(default=None)
    Description = attrib(default=None)
    EnvironmentId = attrib(default=None)
    Tags = attrib(default=None)


@attrs(**ATTRSCONFIG)
class Deployment(Resource):
    """A Deployment for AppConfig.

    See Also:
        `AWS Cloud Formation documentation for Deployment
        <http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-appconfig-deployment.html>`_
    """

    RESOURCE_TYPE = "AWS::AppConfig::Deployment"

    Properties: DeploymentProperties = attrib(
        factory=DeploymentProperties,
        converter=create_object_converter(DeploymentProperties),
    )


@attrs(**ATTRSCONFIG)
class DeploymentStrategyProperties(ResourceProperties):
    DeploymentDurationInMinutes = attrib(default=None)
    Description = attrib(default=None)
    FinalBakeTimeInMinutes = attrib(default=None)
    GrowthFactor = attrib(default=None)
    GrowthType = attrib(default=None)
    Name = attrib(default=None)
    ReplicateTo = attrib(default=None)
    Tags = attrib(default=None)


@attrs(**ATTRSCONFIG)
class DeploymentStrategy(Resource):
    """A Deployment Strategy for AppConfig.

    See Also:
        `AWS Cloud Formation documentation for DeploymentStrategy
        <http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-appconfig-deploymentstrategy.html>`_
    """

    RESOURCE_TYPE = "AWS::AppConfig::DeploymentStrategy"

    Properties: DeploymentStrategyProperties = attrib(
        factory=DeploymentStrategyProperties,
        converter=create_object_converter(DeploymentStrategyProperties),
    )


@attrs(**ATTRSCONFIG)
class EnvironmentProperties(ResourceProperties):
    ApplicationId = attrib(default=None)
    Description = attrib(default=None)
    Monitors = attrib(default=None)
    Name = attrib(default=None)
    Tags = attrib(default=None)


@attrs(**ATTRSCONFIG)
class Environment(Resource):
    """A Environment for AppConfig.

    See Also:
        `AWS Cloud Formation documentation for Environment
        <http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-appconfig-environment.html>`_
    """

    RESOURCE_TYPE = "AWS::AppConfig::Environment"

    Properties: EnvironmentProperties = attrib(
        factory=EnvironmentProperties,
        converter=create_object_converter(EnvironmentProperties),
    )


@attrs(**ATTRSCONFIG)
class HostedConfigurationVersionProperties(ResourceProperties):
    ApplicationId = attrib(default=None)
    ConfigurationProfileId = attrib(default=None)
    Content = attrib(default=None)
    ContentType = attrib(default=None)
    Description = attrib(default=None)
    LatestVersionNumber = attrib(default=None)


@attrs(**ATTRSCONFIG)
class HostedConfigurationVersion(Resource):
    """A Hosted Configuration Version for AppConfig.

    See Also:
        `AWS Cloud Formation documentation for HostedConfigurationVersion
        <http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-appconfig-hostedconfigurationversion.html>`_
    """

    RESOURCE_TYPE = "AWS::AppConfig::HostedConfigurationVersion"

    Properties: HostedConfigurationVersionProperties = attrib(
        factory=HostedConfigurationVersionProperties,
        converter=create_object_converter(HostedConfigurationVersionProperties),
    )
