"""Raw representations of every data type in the AWS AppFlow service.

See Also:
    `AWS developer guide for AppFlow
    <https://docs.aws.amazon.com/appflow/index.html>`_

This file is automatically generated, and should not be directly edited.
"""

from attr import attrib
from attr import attrs

from ..core import ATTRSCONFIG
from ..core import Resource
from ..core import ResourceProperties
from ..core import create_object_converter

__all__ = ["ConnectorProfile", "ConnectorProfileProperties", "Flow", "FlowProperties"]


@attrs(**ATTRSCONFIG)
class ConnectorProfileProperties(ResourceProperties):
    ConnectionMode = attrib(default=None)
    ConnectorProfileConfig = attrib(default=None)
    ConnectorProfileName = attrib(default=None)
    ConnectorType = attrib(default=None)
    KMSArn = attrib(default=None)


@attrs(**ATTRSCONFIG)
class ConnectorProfile(Resource):
    """A Connector Profile for AppFlow.

    See Also:
        `AWS Cloud Formation documentation for ConnectorProfile
        <http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-appflow-connectorprofile.html>`_
    """

    RESOURCE_TYPE = "AWS::AppFlow::ConnectorProfile"

    Properties: ConnectorProfileProperties = attrib(
        factory=ConnectorProfileProperties,
        converter=create_object_converter(ConnectorProfileProperties),
    )


@attrs(**ATTRSCONFIG)
class FlowProperties(ResourceProperties):
    Description = attrib(default=None)
    DestinationFlowConfigList = attrib(default=None)
    FlowName = attrib(default=None)
    KMSArn = attrib(default=None)
    SourceFlowConfig = attrib(default=None)
    Tags = attrib(default=None)
    Tasks = attrib(default=None)
    TriggerConfig = attrib(default=None)


@attrs(**ATTRSCONFIG)
class Flow(Resource):
    """A Flow for AppFlow.

    See Also:
        `AWS Cloud Formation documentation for Flow
        <http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-appflow-flow.html>`_
    """

    RESOURCE_TYPE = "AWS::AppFlow::Flow"

    Properties: FlowProperties = attrib(
        factory=FlowProperties, converter=create_object_converter(FlowProperties)
    )
