"""Raw representations of every data type in the AWS AutoScaling service.

See Also:
    `AWS developer guide for AutoScaling
    <http://docs.aws.amazon.com/autoscaling/latest/userguide/WhatIsAutoScaling.html>`_

This file is automatically generated, and should not be directly edited.
"""

from typing import Any
from typing import Dict

from attr import attrib
from attr import attrs

from ..core import ATTRSCONFIG
from ..core import Resource
from ..core import ResourceProperties
from ..core import create_object_converter

__all__ = [
    "AutoScalingGroup",
    "LaunchConfiguration",
    "LifecycleHook",
    "ScalingPolicy",
    "ScheduledAction",
]


@attrs(**ATTRSCONFIG)
class AutoScalingGroup(Resource):
    """A Auto Scaling Group for AutoScaling.

    See Also:
        `AWS Cloud Formation documentation for AutoScalingGroup
        <http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-as-group.html>`_
    """

    RESOURCE_TYPE = "AWS::AutoScaling::AutoScalingGroup"

    @attrs(**ATTRSCONFIG)
    class PropertiesType(ResourceProperties):
        AutoScalingGroupName = attrib(default=None)
        AvailabilityZones = attrib(default=None)
        Cooldown = attrib(default=None)
        DesiredCapacity = attrib(default=None)
        HealthCheckGracePeriod = attrib(default=None)
        HealthCheckType = attrib(default=None)
        InstanceId = attrib(default=None)
        LaunchConfigurationName = attrib(default=None)
        LaunchTemplate = attrib(default=None)
        LifecycleHookSpecificationList = attrib(default=None)
        LoadBalancerNames = attrib(default=None)
        MaxSize = attrib(default=None)
        MetricsCollection = attrib(default=None)
        MinSize = attrib(default=None)
        NotificationConfigurations = attrib(default=None)
        PlacementGroup = attrib(default=None)
        ServiceLinkedRoleARN = attrib(default=None)
        Tags = attrib(default=None)
        TargetGroupARNs = attrib(default=None)
        TerminationPolicies = attrib(default=None)
        VPCZoneIdentifier = attrib(default=None)

    Properties: PropertiesType = attrib(factory=PropertiesType, converter=create_object_converter(PropertiesType))

    # NB: UpdatePolicy may be set for AutoScalingGroup
    # (unlike most Resource types)
    UpdatePolicy: Dict[str, Any] = attrib(factory=dict)


@attrs(**ATTRSCONFIG)
class LaunchConfiguration(Resource):
    """A Launch Configuration for AutoScaling.

    See Also:
        `AWS Cloud Formation documentation for LaunchConfiguration
        <http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-as-launchconfig.html>`_
    """

    RESOURCE_TYPE = "AWS::AutoScaling::LaunchConfiguration"

    @attrs(**ATTRSCONFIG)
    class PropertiesType(ResourceProperties):
        AssociatePublicIpAddress = attrib(default=None)
        BlockDeviceMappings = attrib(default=None)
        ClassicLinkVPCId = attrib(default=None)
        ClassicLinkVPCSecurityGroups = attrib(default=None)
        EbsOptimized = attrib(default=None)
        IamInstanceProfile = attrib(default=None)
        ImageId = attrib(default=None)
        InstanceId = attrib(default=None)
        InstanceMonitoring = attrib(default=None)
        InstanceType = attrib(default=None)
        KernelId = attrib(default=None)
        KeyName = attrib(default=None)
        LaunchConfigurationName = attrib(default=None)
        PlacementTenancy = attrib(default=None)
        RamDiskId = attrib(default=None)
        SecurityGroups = attrib(default=None)
        SpotPrice = attrib(default=None)
        UserData = attrib(default=None)

    Properties: PropertiesType = attrib(factory=PropertiesType, converter=create_object_converter(PropertiesType))


@attrs(**ATTRSCONFIG)
class LifecycleHook(Resource):
    """A Lifecycle Hook for AutoScaling.

    See Also:
        `AWS Cloud Formation documentation for LifecycleHook
        <http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-as-lifecyclehook.html>`_
    """

    RESOURCE_TYPE = "AWS::AutoScaling::LifecycleHook"

    @attrs(**ATTRSCONFIG)
    class PropertiesType(ResourceProperties):
        AutoScalingGroupName = attrib(default=None)
        DefaultResult = attrib(default=None)
        HeartbeatTimeout = attrib(default=None)
        LifecycleHookName = attrib(default=None)
        LifecycleTransition = attrib(default=None)
        NotificationMetadata = attrib(default=None)
        NotificationTargetARN = attrib(default=None)
        RoleARN = attrib(default=None)

    Properties: PropertiesType = attrib(factory=PropertiesType, converter=create_object_converter(PropertiesType))


@attrs(**ATTRSCONFIG)
class ScalingPolicy(Resource):
    """A Scaling Policy for AutoScaling.

    See Also:
        `AWS Cloud Formation documentation for ScalingPolicy
        <http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-as-policy.html>`_
    """

    RESOURCE_TYPE = "AWS::AutoScaling::ScalingPolicy"

    @attrs(**ATTRSCONFIG)
    class PropertiesType(ResourceProperties):
        AdjustmentType = attrib(default=None)
        AutoScalingGroupName = attrib(default=None)
        Cooldown = attrib(default=None)
        EstimatedInstanceWarmup = attrib(default=None)
        MetricAggregationType = attrib(default=None)
        MinAdjustmentMagnitude = attrib(default=None)
        PolicyType = attrib(default=None)
        ScalingAdjustment = attrib(default=None)
        StepAdjustments = attrib(default=None)
        TargetTrackingConfiguration = attrib(default=None)

    Properties: PropertiesType = attrib(factory=PropertiesType, converter=create_object_converter(PropertiesType))


@attrs(**ATTRSCONFIG)
class ScheduledAction(Resource):
    """A Scheduled Action for AutoScaling.

    See Also:
        `AWS Cloud Formation documentation for ScheduledAction
        <http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-as-scheduledaction.html>`_
    """

    RESOURCE_TYPE = "AWS::AutoScaling::ScheduledAction"

    @attrs(**ATTRSCONFIG)
    class PropertiesType(ResourceProperties):
        AutoScalingGroupName = attrib(default=None)
        DesiredCapacity = attrib(default=None)
        EndTime = attrib(default=None)
        MaxSize = attrib(default=None)
        MinSize = attrib(default=None)
        Recurrence = attrib(default=None)
        StartTime = attrib(default=None)

    Properties: PropertiesType = attrib(factory=PropertiesType, converter=create_object_converter(PropertiesType))
