"""Raw representations of every data type in the AWS CE service.

See Also:
    `AWS developer guide for CE
    <https://aws.amazon.com/aws-cost-management/aws-cost-explorer/>`_

This file is automatically generated, and should not be directly edited.
"""

from attr import attrib
from attr import attrs

from ..core import ATTRSCONFIG
from ..core import Resource
from ..core import ResourceProperties
from ..core import create_object_converter

__all__ = ["CostCategory", "CostCategoryProperties"]


@attrs(**ATTRSCONFIG)
class CostCategoryProperties(ResourceProperties):
    Name = attrib(default=None)
    Rules = attrib(default=None)
    RuleVersion = attrib(default=None)


@attrs(**ATTRSCONFIG)
class CostCategory(Resource):
    """A Cost Category for CE.

    See Also:
        `AWS Cloud Formation documentation for CostCategory
        <http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-ce-costcategory.html>`_
    """

    RESOURCE_TYPE = "AWS::CE::CostCategory"

    Properties: CostCategoryProperties = attrib(
        factory=CostCategoryProperties,
        converter=create_object_converter(CostCategoryProperties),
    )
