"""Raw representations of every data type in the AWS Chatbot service.

See Also:
    `AWS developer guide for Chatbot
    <https://docs.aws.amazon.com/chatbot/latest/adminguide/index.html>`_

This file is automatically generated, and should not be directly edited.
"""

from attr import attrib
from attr import attrs

from ..core import ATTRSCONFIG
from ..core import Resource
from ..core import ResourceProperties
from ..core import create_object_converter

__all__ = ["SlackChannelConfiguration", "SlackChannelConfigurationProperties"]


@attrs(**ATTRSCONFIG)
class SlackChannelConfigurationProperties(ResourceProperties):
    ConfigurationName = attrib(default=None)
    IamRoleArn = attrib(default=None)
    LoggingLevel = attrib(default=None)
    SlackChannelId = attrib(default=None)
    SlackWorkspaceId = attrib(default=None)
    SnsTopicArns = attrib(default=None)


@attrs(**ATTRSCONFIG)
class SlackChannelConfiguration(Resource):
    """A Slack Channel Configuration for Chatbot.

    See Also:
        `AWS Cloud Formation documentation for SlackChannelConfiguration
        <http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-chatbot-slackchannelconfiguration.html>`_
    """

    RESOURCE_TYPE = "AWS::Chatbot::SlackChannelConfiguration"

    Properties: SlackChannelConfigurationProperties = attrib(
        factory=SlackChannelConfigurationProperties,
        converter=create_object_converter(SlackChannelConfigurationProperties),
    )
