"""Raw representations of every data type in the AWS CodeGuruProfiler service.

See Also:
    `AWS developer guide for CodeGuruProfiler
    <https://aws.amazon.com/codeguru/>`_

This file is automatically generated, and should not be directly edited.
"""

from attr import attrib
from attr import attrs

from ..core import ATTRSCONFIG
from ..core import Resource
from ..core import ResourceProperties
from ..core import create_object_converter

__all__ = ["ProfilingGroup", "ProfilingGroupProperties"]


@attrs(**ATTRSCONFIG)
class ProfilingGroupProperties(ResourceProperties):
    AgentPermissions = attrib(default=None)
    AnomalyDetectionNotificationConfiguration = attrib(default=None)
    ComputePlatform = attrib(default=None)
    ProfilingGroupName = attrib(default=None)
    Tags = attrib(default=None)


@attrs(**ATTRSCONFIG)
class ProfilingGroup(Resource):
    """A Profiling Group for CodeGuruProfiler.

    See Also:
        `AWS Cloud Formation documentation for ProfilingGroup
        <http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-codeguruprofiler-profilinggroup.html>`_
    """

    RESOURCE_TYPE = "AWS::CodeGuruProfiler::ProfilingGroup"

    Properties: ProfilingGroupProperties = attrib(
        factory=ProfilingGroupProperties,
        converter=create_object_converter(ProfilingGroupProperties),
    )
