"""Raw representations of every data type in the AWS CodeGuruReviewer service.

See Also:
    `AWS developer guide for CodeGuruReviewer
    <https://aws.amazon.com/codeguru/>`_

This file is automatically generated, and should not be directly edited.
"""

from attr import attrib
from attr import attrs

from ..core import ATTRSCONFIG
from ..core import Resource
from ..core import ResourceProperties
from ..core import create_object_converter

__all__ = ["RepositoryAssociation", "RepositoryAssociationProperties"]


@attrs(**ATTRSCONFIG)
class RepositoryAssociationProperties(ResourceProperties):
    ConnectionArn = attrib(default=None)
    Name = attrib(default=None)
    Owner = attrib(default=None)
    Type = attrib(default=None)


@attrs(**ATTRSCONFIG)
class RepositoryAssociation(Resource):
    """A Repository Association for CodeGuruReviewer.

    See Also:
        `AWS Cloud Formation documentation for RepositoryAssociation
        <http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-codegurureviewer-repositoryassociation.html>`_
    """

    RESOURCE_TYPE = "AWS::CodeGuruReviewer::RepositoryAssociation"

    Properties: RepositoryAssociationProperties = attrib(
        factory=RepositoryAssociationProperties,
        converter=create_object_converter(RepositoryAssociationProperties),
    )
