"""Raw representations of every data type in the AWS EFS service.

See Also:
    `AWS developer guide for EFS
    <https://docs.aws.amazon.com/efs/latest/ug/index.html>`_

This file is automatically generated, and should not be directly edited.
"""

from attr import attrib
from attr import attrs

from ..core import ATTRSCONFIG
from ..core import Resource
from ..core import ResourceProperties
from ..core import create_object_converter

__all__ = ["FileSystem", "FileSystemProperties", "MountTarget", "MountTargetProperties"]


@attrs(**ATTRSCONFIG)
class FileSystemProperties(ResourceProperties):
    Encrypted = attrib(default=None)
    FileSystemTags = attrib(default=None)
    KmsKeyId = attrib(default=None)
    LifecyclePolicies = attrib(default=None)
    PerformanceMode = attrib(default=None)
    ProvisionedThroughputInMibps = attrib(default=None)
    ThroughputMode = attrib(default=None)


@attrs(**ATTRSCONFIG)
class FileSystem(Resource):
    """A File System for EFS.

    See Also:
        `AWS Cloud Formation documentation for FileSystem
        <http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-efs-filesystem.html>`_
    """

    RESOURCE_TYPE = "AWS::EFS::FileSystem"

    Properties: FileSystemProperties = attrib(
        factory=FileSystemProperties,
        converter=create_object_converter(FileSystemProperties),
    )


@attrs(**ATTRSCONFIG)
class MountTargetProperties(ResourceProperties):
    FileSystemId = attrib(default=None)
    IpAddress = attrib(default=None)
    SecurityGroups = attrib(default=None)
    SubnetId = attrib(default=None)


@attrs(**ATTRSCONFIG)
class MountTarget(Resource):
    """A Mount Target for EFS.

    See Also:
        `AWS Cloud Formation documentation for MountTarget
        <http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-efs-mounttarget.html>`_
    """

    RESOURCE_TYPE = "AWS::EFS::MountTarget"

    Properties: MountTargetProperties = attrib(
        factory=MountTargetProperties,
        converter=create_object_converter(MountTargetProperties),
    )
