"""Raw representations of every data type in the AWS FMS service.

See Also:
    `AWS developer guide for FMS
    <https://docs.aws.amazon.com/waf/latest/developerguide/fms-chapter.html>`_

This file is automatically generated, and should not be directly edited.
"""

from attr import attrib
from attr import attrs

from ..core import ATTRSCONFIG
from ..core import Resource
from ..core import ResourceProperties
from ..core import create_object_converter

__all__ = [
    "NotificationChannel",
    "NotificationChannelProperties",
    "Policy",
    "PolicyProperties",
]


@attrs(**ATTRSCONFIG)
class NotificationChannelProperties(ResourceProperties):
    SnsRoleName = attrib(default=None)
    SnsTopicArn = attrib(default=None)


@attrs(**ATTRSCONFIG)
class NotificationChannel(Resource):
    """A Notification Channel for FMS.

    See Also:
        `AWS Cloud Formation documentation for NotificationChannel
        <http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-fms-notificationchannel.html>`_
    """

    RESOURCE_TYPE = "AWS::FMS::NotificationChannel"

    Properties: NotificationChannelProperties = attrib(
        factory=NotificationChannelProperties,
        converter=create_object_converter(NotificationChannelProperties),
    )


@attrs(**ATTRSCONFIG)
class PolicyProperties(ResourceProperties):
    DeleteAllPolicyResources = attrib(default=None)
    ExcludeMap = attrib(default=None)
    ExcludeResourceTags = attrib(default=None)
    IncludeMap = attrib(default=None)
    PolicyName = attrib(default=None)
    RemediationEnabled = attrib(default=None)
    ResourceTags = attrib(default=None)
    ResourceType = attrib(default=None)
    ResourceTypeList = attrib(default=None)
    SecurityServicePolicyData = attrib(default=None)
    Tags = attrib(default=None)


@attrs(**ATTRSCONFIG)
class Policy(Resource):
    """A Policy for FMS.

    See Also:
        `AWS Cloud Formation documentation for Policy
        <http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-fms-policy.html>`_
    """

    RESOURCE_TYPE = "AWS::FMS::Policy"

    Properties: PolicyProperties = attrib(
        factory=PolicyProperties, converter=create_object_converter(PolicyProperties)
    )
