"""Raw representations of every data type in the AWS GlobalAccelerator service.

See Also:
    `AWS developer guide for GlobalAccelerator
    <https://docs.aws.amazon.com/global-accelerator/latest/dg/getting-started.html>`_

This file is automatically generated, and should not be directly edited.
"""

from attr import attrib
from attr import attrs

from ..core import ATTRSCONFIG
from ..core import Resource
from ..core import ResourceProperties
from ..core import create_object_converter

__all__ = [
    "Accelerator",
    "AcceleratorProperties",
    "EndpointGroup",
    "EndpointGroupProperties",
    "Listener",
    "ListenerProperties",
]


@attrs(**ATTRSCONFIG)
class AcceleratorProperties(ResourceProperties):
    Enabled = attrib(default=None)
    IpAddresses = attrib(default=None)
    IpAddressType = attrib(default=None)
    Name = attrib(default=None)
    Tags = attrib(default=None)


@attrs(**ATTRSCONFIG)
class Accelerator(Resource):
    """A Accelerator for GlobalAccelerator.

    See Also:
        `AWS Cloud Formation documentation for Accelerator
        <http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-globalaccelerator-accelerator.html>`_
    """

    RESOURCE_TYPE = "AWS::GlobalAccelerator::Accelerator"

    Properties: AcceleratorProperties = attrib(
        factory=AcceleratorProperties,
        converter=create_object_converter(AcceleratorProperties),
    )


@attrs(**ATTRSCONFIG)
class EndpointGroupProperties(ResourceProperties):
    EndpointConfigurations = attrib(default=None)
    EndpointGroupRegion = attrib(default=None)
    HealthCheckIntervalSeconds = attrib(default=None)
    HealthCheckPath = attrib(default=None)
    HealthCheckPort = attrib(default=None)
    HealthCheckProtocol = attrib(default=None)
    ListenerArn = attrib(default=None)
    PortOverrides = attrib(default=None)
    ThresholdCount = attrib(default=None)
    TrafficDialPercentage = attrib(default=None)


@attrs(**ATTRSCONFIG)
class EndpointGroup(Resource):
    """A Endpoint Group for GlobalAccelerator.

    See Also:
        `AWS Cloud Formation documentation for EndpointGroup
        <http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-globalaccelerator-endpointgroup.html>`_
    """

    RESOURCE_TYPE = "AWS::GlobalAccelerator::EndpointGroup"

    Properties: EndpointGroupProperties = attrib(
        factory=EndpointGroupProperties,
        converter=create_object_converter(EndpointGroupProperties),
    )


@attrs(**ATTRSCONFIG)
class ListenerProperties(ResourceProperties):
    AcceleratorArn = attrib(default=None)
    ClientAffinity = attrib(default=None)
    PortRanges = attrib(default=None)
    Protocol = attrib(default=None)


@attrs(**ATTRSCONFIG)
class Listener(Resource):
    """A Listener for GlobalAccelerator.

    See Also:
        `AWS Cloud Formation documentation for Listener
        <http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-globalaccelerator-listener.html>`_
    """

    RESOURCE_TYPE = "AWS::GlobalAccelerator::Listener"

    Properties: ListenerProperties = attrib(
        factory=ListenerProperties,
        converter=create_object_converter(ListenerProperties),
    )
