"""Raw representations of every data type in the AWS ImageBuilder service.

See Also:
    `AWS developer guide for ImageBuilder
    <https://aws.amazon.com/image-builder/>`_

This file is automatically generated, and should not be directly edited.
"""

from attr import attrib
from attr import attrs

from ..core import ATTRSCONFIG
from ..core import Resource
from ..core import ResourceProperties
from ..core import create_object_converter

__all__ = [
    "Component",
    "ComponentProperties",
    "DistributionConfiguration",
    "DistributionConfigurationProperties",
    "Image",
    "ImageProperties",
    "ImagePipeline",
    "ImagePipelineProperties",
    "ImageRecipe",
    "ImageRecipeProperties",
    "InfrastructureConfiguration",
    "InfrastructureConfigurationProperties",
]


@attrs(**ATTRSCONFIG)
class ComponentProperties(ResourceProperties):
    ChangeDescription = attrib(default=None)
    Data = attrib(default=None)
    Description = attrib(default=None)
    KmsKeyId = attrib(default=None)
    Name = attrib(default=None)
    Platform = attrib(default=None)
    SupportedOsVersions = attrib(default=None)
    Tags = attrib(default=None)
    Uri = attrib(default=None)
    Version = attrib(default=None)


@attrs(**ATTRSCONFIG)
class Component(Resource):
    """A Component for ImageBuilder.

    See Also:
        `AWS Cloud Formation documentation for Component
        <http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-imagebuilder-component.html>`_
    """

    RESOURCE_TYPE = "AWS::ImageBuilder::Component"

    Properties: ComponentProperties = attrib(
        factory=ComponentProperties,
        converter=create_object_converter(ComponentProperties),
    )


@attrs(**ATTRSCONFIG)
class DistributionConfigurationProperties(ResourceProperties):
    Description = attrib(default=None)
    Distributions = attrib(default=None)
    Name = attrib(default=None)
    Tags = attrib(default=None)


@attrs(**ATTRSCONFIG)
class DistributionConfiguration(Resource):
    """A Distribution Configuration for ImageBuilder.

    See Also:
        `AWS Cloud Formation documentation for DistributionConfiguration
        <http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-imagebuilder-distributionconfiguration.html>`_
    """

    RESOURCE_TYPE = "AWS::ImageBuilder::DistributionConfiguration"

    Properties: DistributionConfigurationProperties = attrib(
        factory=DistributionConfigurationProperties,
        converter=create_object_converter(DistributionConfigurationProperties),
    )


@attrs(**ATTRSCONFIG)
class ImageProperties(ResourceProperties):
    DistributionConfigurationArn = attrib(default=None)
    EnhancedImageMetadataEnabled = attrib(default=None)
    ImageRecipeArn = attrib(default=None)
    ImageTestsConfiguration = attrib(default=None)
    InfrastructureConfigurationArn = attrib(default=None)
    Tags = attrib(default=None)


@attrs(**ATTRSCONFIG)
class Image(Resource):
    """A Image for ImageBuilder.

    See Also:
        `AWS Cloud Formation documentation for Image
        <http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-imagebuilder-image.html>`_
    """

    RESOURCE_TYPE = "AWS::ImageBuilder::Image"

    Properties: ImageProperties = attrib(
        factory=ImageProperties, converter=create_object_converter(ImageProperties)
    )


@attrs(**ATTRSCONFIG)
class ImagePipelineProperties(ResourceProperties):
    Description = attrib(default=None)
    DistributionConfigurationArn = attrib(default=None)
    EnhancedImageMetadataEnabled = attrib(default=None)
    ImageRecipeArn = attrib(default=None)
    ImageTestsConfiguration = attrib(default=None)
    InfrastructureConfigurationArn = attrib(default=None)
    Name = attrib(default=None)
    Schedule = attrib(default=None)
    Status = attrib(default=None)
    Tags = attrib(default=None)


@attrs(**ATTRSCONFIG)
class ImagePipeline(Resource):
    """A Image Pipeline for ImageBuilder.

    See Also:
        `AWS Cloud Formation documentation for ImagePipeline
        <http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-imagebuilder-imagepipeline.html>`_
    """

    RESOURCE_TYPE = "AWS::ImageBuilder::ImagePipeline"

    Properties: ImagePipelineProperties = attrib(
        factory=ImagePipelineProperties,
        converter=create_object_converter(ImagePipelineProperties),
    )


@attrs(**ATTRSCONFIG)
class ImageRecipeProperties(ResourceProperties):
    BlockDeviceMappings = attrib(default=None)
    Components = attrib(default=None)
    Description = attrib(default=None)
    Name = attrib(default=None)
    ParentImage = attrib(default=None)
    Tags = attrib(default=None)
    Version = attrib(default=None)
    WorkingDirectory = attrib(default=None)


@attrs(**ATTRSCONFIG)
class ImageRecipe(Resource):
    """A Image Recipe for ImageBuilder.

    See Also:
        `AWS Cloud Formation documentation for ImageRecipe
        <http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-imagebuilder-imagerecipe.html>`_
    """

    RESOURCE_TYPE = "AWS::ImageBuilder::ImageRecipe"

    Properties: ImageRecipeProperties = attrib(
        factory=ImageRecipeProperties,
        converter=create_object_converter(ImageRecipeProperties),
    )


@attrs(**ATTRSCONFIG)
class InfrastructureConfigurationProperties(ResourceProperties):
    Description = attrib(default=None)
    InstanceProfileName = attrib(default=None)
    InstanceTypes = attrib(default=None)
    KeyPair = attrib(default=None)
    Logging = attrib(default=None)
    Name = attrib(default=None)
    ResourceTags = attrib(default=None)
    SecurityGroupIds = attrib(default=None)
    SnsTopicArn = attrib(default=None)
    SubnetId = attrib(default=None)
    Tags = attrib(default=None)
    TerminateInstanceOnFailure = attrib(default=None)


@attrs(**ATTRSCONFIG)
class InfrastructureConfiguration(Resource):
    """A Infrastructure Configuration for ImageBuilder.

    See Also:
        `AWS Cloud Formation documentation for InfrastructureConfiguration
        <http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-imagebuilder-infrastructureconfiguration.html>`_
    """

    RESOURCE_TYPE = "AWS::ImageBuilder::InfrastructureConfiguration"

    Properties: InfrastructureConfigurationProperties = attrib(
        factory=InfrastructureConfigurationProperties,
        converter=create_object_converter(InfrastructureConfigurationProperties),
    )
