"""Raw representations of every data type in the AWS IoTSiteWise service.

See Also:
    `AWS developer guide for IoTSiteWise
    <https://docs.aws.amazon.com/iot-sitewise/latest/userguide/index.html>`_

This file is automatically generated, and should not be directly edited.
"""

from attr import attrib
from attr import attrs

from ..core import ATTRSCONFIG
from ..core import Resource
from ..core import ResourceProperties
from ..core import create_object_converter

__all__ = [
    "Asset",
    "AssetProperties",
    "AssetModel",
    "AssetModelProperties",
    "Gateway",
    "GatewayProperties",
]


@attrs(**ATTRSCONFIG)
class AssetProperties(ResourceProperties):
    AssetHierarchies = attrib(default=None)
    AssetModelId = attrib(default=None)
    AssetName = attrib(default=None)
    AssetProperties = attrib(default=None)
    Tags = attrib(default=None)


@attrs(**ATTRSCONFIG)
class Asset(Resource):
    """A Asset for IoTSiteWise.

    See Also:
        `AWS Cloud Formation documentation for Asset
        <http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-iotsitewise-asset.html>`_
    """

    RESOURCE_TYPE = "AWS::IoTSiteWise::Asset"

    Properties: AssetProperties = attrib(
        factory=AssetProperties, converter=create_object_converter(AssetProperties)
    )


@attrs(**ATTRSCONFIG)
class AssetModelProperties(ResourceProperties):
    AssetModelDescription = attrib(default=None)
    AssetModelHierarchies = attrib(default=None)
    AssetModelName = attrib(default=None)
    AssetModelProperties = attrib(default=None)
    Tags = attrib(default=None)


@attrs(**ATTRSCONFIG)
class AssetModel(Resource):
    """A Asset Model for IoTSiteWise.

    See Also:
        `AWS Cloud Formation documentation for AssetModel
        <http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-iotsitewise-assetmodel.html>`_
    """

    RESOURCE_TYPE = "AWS::IoTSiteWise::AssetModel"

    Properties: AssetModelProperties = attrib(
        factory=AssetModelProperties,
        converter=create_object_converter(AssetModelProperties),
    )


@attrs(**ATTRSCONFIG)
class GatewayProperties(ResourceProperties):
    GatewayCapabilitySummaries = attrib(default=None)
    GatewayName = attrib(default=None)
    GatewayPlatform = attrib(default=None)
    Tags = attrib(default=None)


@attrs(**ATTRSCONFIG)
class Gateway(Resource):
    """A Gateway for IoTSiteWise.

    See Also:
        `AWS Cloud Formation documentation for Gateway
        <http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-iotsitewise-gateway.html>`_
    """

    RESOURCE_TYPE = "AWS::IoTSiteWise::Gateway"

    Properties: GatewayProperties = attrib(
        factory=GatewayProperties, converter=create_object_converter(GatewayProperties)
    )
