"""Raw representations of every data type in the AWS IVS service.

See Also:
    `AWS developer guide for IVS
    <https://docs.aws.amazon.com/ivs/latest/userguide/index.html>`_

This file is automatically generated, and should not be directly edited.
"""

from attr import attrib
from attr import attrs

from ..core import ATTRSCONFIG
from ..core import Resource
from ..core import ResourceProperties
from ..core import create_object_converter

__all__ = [
    "Channel",
    "ChannelProperties",
    "PlaybackKeyPair",
    "PlaybackKeyPairProperties",
    "StreamKey",
    "StreamKeyProperties",
]


@attrs(**ATTRSCONFIG)
class ChannelProperties(ResourceProperties):
    Authorized = attrib(default=None)
    LatencyMode = attrib(default=None)
    Name = attrib(default=None)
    Tags = attrib(default=None)
    Type = attrib(default=None)


@attrs(**ATTRSCONFIG)
class Channel(Resource):
    """A Channel for IVS.

    See Also:
        `AWS Cloud Formation documentation for Channel
        <http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-ivs-channel.html>`_
    """

    RESOURCE_TYPE = "AWS::IVS::Channel"

    Properties: ChannelProperties = attrib(
        factory=ChannelProperties, converter=create_object_converter(ChannelProperties)
    )


@attrs(**ATTRSCONFIG)
class PlaybackKeyPairProperties(ResourceProperties):
    Name = attrib(default=None)
    PublicKeyMaterial = attrib(default=None)
    Tags = attrib(default=None)


@attrs(**ATTRSCONFIG)
class PlaybackKeyPair(Resource):
    """A Playback Key Pair for IVS.

    See Also:
        `AWS Cloud Formation documentation for PlaybackKeyPair
        <http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-ivs-playbackkeypair.html>`_
    """

    RESOURCE_TYPE = "AWS::IVS::PlaybackKeyPair"

    Properties: PlaybackKeyPairProperties = attrib(
        factory=PlaybackKeyPairProperties,
        converter=create_object_converter(PlaybackKeyPairProperties),
    )


@attrs(**ATTRSCONFIG)
class StreamKeyProperties(ResourceProperties):
    ChannelArn = attrib(default=None)
    Tags = attrib(default=None)


@attrs(**ATTRSCONFIG)
class StreamKey(Resource):
    """A Stream Key for IVS.

    See Also:
        `AWS Cloud Formation documentation for StreamKey
        <http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-ivs-streamkey.html>`_
    """

    RESOURCE_TYPE = "AWS::IVS::StreamKey"

    Properties: StreamKeyProperties = attrib(
        factory=StreamKeyProperties,
        converter=create_object_converter(StreamKeyProperties),
    )
