"""Raw representations of every data type in the AWS Kendra service.

See Also:
    `AWS developer guide for Kendra
    <http://docs.aws.amazon.com/kendra/latest/dg/>`_

This file is automatically generated, and should not be directly edited.
"""

from attr import attrib
from attr import attrs

from ..core import ATTRSCONFIG
from ..core import Resource
from ..core import ResourceProperties
from ..core import create_object_converter

__all__ = [
    "DataSource",
    "DataSourceProperties",
    "Faq",
    "FaqProperties",
    "Index",
    "IndexProperties",
]


@attrs(**ATTRSCONFIG)
class DataSourceProperties(ResourceProperties):
    DataSourceConfiguration = attrib(default=None)
    Description = attrib(default=None)
    IndexId = attrib(default=None)
    Name = attrib(default=None)
    RoleArn = attrib(default=None)
    Schedule = attrib(default=None)
    Tags = attrib(default=None)
    Type = attrib(default=None)


@attrs(**ATTRSCONFIG)
class DataSource(Resource):
    """A Data Source for Kendra.

    See Also:
        `AWS Cloud Formation documentation for DataSource
        <http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-kendra-datasource.html>`_
    """

    RESOURCE_TYPE = "AWS::Kendra::DataSource"

    Properties: DataSourceProperties = attrib(
        factory=DataSourceProperties,
        converter=create_object_converter(DataSourceProperties),
    )


@attrs(**ATTRSCONFIG)
class FaqProperties(ResourceProperties):
    Description = attrib(default=None)
    FileFormat = attrib(default=None)
    IndexId = attrib(default=None)
    Name = attrib(default=None)
    RoleArn = attrib(default=None)
    S3Path = attrib(default=None)
    Tags = attrib(default=None)


@attrs(**ATTRSCONFIG)
class Faq(Resource):
    """A Faq for Kendra.

    See Also:
        `AWS Cloud Formation documentation for Faq
        <http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-kendra-faq.html>`_
    """

    RESOURCE_TYPE = "AWS::Kendra::Faq"

    Properties: FaqProperties = attrib(
        factory=FaqProperties, converter=create_object_converter(FaqProperties)
    )


@attrs(**ATTRSCONFIG)
class IndexProperties(ResourceProperties):
    CapacityUnits = attrib(default=None)
    Description = attrib(default=None)
    DocumentMetadataConfigurations = attrib(default=None)
    Edition = attrib(default=None)
    Name = attrib(default=None)
    RoleArn = attrib(default=None)
    ServerSideEncryptionConfiguration = attrib(default=None)
    Tags = attrib(default=None)


@attrs(**ATTRSCONFIG)
class Index(Resource):
    """A Index for Kendra.

    See Also:
        `AWS Cloud Formation documentation for Index
        <http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-kendra-index.html>`_
    """

    RESOURCE_TYPE = "AWS::Kendra::Index"

    Properties: IndexProperties = attrib(
        factory=IndexProperties, converter=create_object_converter(IndexProperties)
    )
