"""Raw representations of every data type in the AWS Macie service.

See Also:
    `AWS developer guide for Macie
    <https://docs.aws.amazon.com/macie/>`_

This file is automatically generated, and should not be directly edited.
"""

from attr import attrib
from attr import attrs

from ..core import ATTRSCONFIG
from ..core import Resource
from ..core import ResourceProperties
from ..core import create_object_converter

__all__ = [
    "CustomDataIdentifier",
    "CustomDataIdentifierProperties",
    "FindingsFilter",
    "FindingsFilterProperties",
    "Session",
    "SessionProperties",
]


@attrs(**ATTRSCONFIG)
class CustomDataIdentifierProperties(ResourceProperties):
    Description = attrib(default=None)
    IgnoreWords = attrib(default=None)
    Keywords = attrib(default=None)
    MaximumMatchDistance = attrib(default=None)
    Name = attrib(default=None)
    Regex = attrib(default=None)


@attrs(**ATTRSCONFIG)
class CustomDataIdentifier(Resource):
    """A Custom Data Identifier for Macie.

    See Also:
        `AWS Cloud Formation documentation for CustomDataIdentifier
        <http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-macie-customdataidentifier.html>`_
    """

    RESOURCE_TYPE = "AWS::Macie::CustomDataIdentifier"

    Properties: CustomDataIdentifierProperties = attrib(
        factory=CustomDataIdentifierProperties,
        converter=create_object_converter(CustomDataIdentifierProperties),
    )


@attrs(**ATTRSCONFIG)
class FindingsFilterProperties(ResourceProperties):
    Action = attrib(default=None)
    Description = attrib(default=None)
    FindingCriteria = attrib(default=None)
    Name = attrib(default=None)
    Position = attrib(default=None)


@attrs(**ATTRSCONFIG)
class FindingsFilter(Resource):
    """A Findings Filter for Macie.

    See Also:
        `AWS Cloud Formation documentation for FindingsFilter
        <http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-macie-findingsfilter.html>`_
    """

    RESOURCE_TYPE = "AWS::Macie::FindingsFilter"

    Properties: FindingsFilterProperties = attrib(
        factory=FindingsFilterProperties,
        converter=create_object_converter(FindingsFilterProperties),
    )


@attrs(**ATTRSCONFIG)
class SessionProperties(ResourceProperties):
    FindingPublishingFrequency = attrib(default=None)
    Status = attrib(default=None)


@attrs(**ATTRSCONFIG)
class Session(Resource):
    """A Session for Macie.

    See Also:
        `AWS Cloud Formation documentation for Session
        <http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-macie-session.html>`_
    """

    RESOURCE_TYPE = "AWS::Macie::Session"

    Properties: SessionProperties = attrib(
        factory=SessionProperties, converter=create_object_converter(SessionProperties)
    )
