"""Raw representations of every data type in the AWS MediaPackage service.

See Also:
    `AWS developer guide for MediaPackage
    <http://docs.aws.amazon.com/mediapackage/latest/ug/what-is.html>`_

This file is automatically generated, and should not be directly edited.
"""

from attr import attrib
from attr import attrs

from ..core import ATTRSCONFIG
from ..core import Resource
from ..core import ResourceProperties
from ..core import create_object_converter

__all__ = [
    "Asset",
    "AssetProperties",
    "Channel",
    "ChannelProperties",
    "OriginEndpoint",
    "OriginEndpointProperties",
    "PackagingConfiguration",
    "PackagingConfigurationProperties",
    "PackagingGroup",
    "PackagingGroupProperties",
]


@attrs(**ATTRSCONFIG)
class AssetProperties(ResourceProperties):
    EgressEndpoints = attrib(default=None)
    Id = attrib(default=None)
    PackagingGroupId = attrib(default=None)
    ResourceId = attrib(default=None)
    SourceArn = attrib(default=None)
    SourceRoleArn = attrib(default=None)
    Tags = attrib(default=None)


@attrs(**ATTRSCONFIG)
class Asset(Resource):
    """A Asset for MediaPackage.

    See Also:
        `AWS Cloud Formation documentation for Asset
        <http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-mediapackage-asset.html>`_
    """

    RESOURCE_TYPE = "AWS::MediaPackage::Asset"

    Properties: AssetProperties = attrib(
        factory=AssetProperties, converter=create_object_converter(AssetProperties)
    )


@attrs(**ATTRSCONFIG)
class ChannelProperties(ResourceProperties):
    Description = attrib(default=None)
    Id = attrib(default=None)
    Tags = attrib(default=None)


@attrs(**ATTRSCONFIG)
class Channel(Resource):
    """A Channel for MediaPackage.

    See Also:
        `AWS Cloud Formation documentation for Channel
        <http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-mediapackage-channel.html>`_
    """

    RESOURCE_TYPE = "AWS::MediaPackage::Channel"

    Properties: ChannelProperties = attrib(
        factory=ChannelProperties, converter=create_object_converter(ChannelProperties)
    )


@attrs(**ATTRSCONFIG)
class OriginEndpointProperties(ResourceProperties):
    Authorization = attrib(default=None)
    ChannelId = attrib(default=None)
    CmafPackage = attrib(default=None)
    DashPackage = attrib(default=None)
    Description = attrib(default=None)
    HlsPackage = attrib(default=None)
    Id = attrib(default=None)
    ManifestName = attrib(default=None)
    MssPackage = attrib(default=None)
    Origination = attrib(default=None)
    StartoverWindowSeconds = attrib(default=None)
    Tags = attrib(default=None)
    TimeDelaySeconds = attrib(default=None)
    Whitelist = attrib(default=None)


@attrs(**ATTRSCONFIG)
class OriginEndpoint(Resource):
    """A Origin Endpoint for MediaPackage.

    See Also:
        `AWS Cloud Formation documentation for OriginEndpoint
        <http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-mediapackage-originendpoint.html>`_
    """

    RESOURCE_TYPE = "AWS::MediaPackage::OriginEndpoint"

    Properties: OriginEndpointProperties = attrib(
        factory=OriginEndpointProperties,
        converter=create_object_converter(OriginEndpointProperties),
    )


@attrs(**ATTRSCONFIG)
class PackagingConfigurationProperties(ResourceProperties):
    CmafPackage = attrib(default=None)
    DashPackage = attrib(default=None)
    HlsPackage = attrib(default=None)
    Id = attrib(default=None)
    MssPackage = attrib(default=None)
    PackagingGroupId = attrib(default=None)
    Tags = attrib(default=None)


@attrs(**ATTRSCONFIG)
class PackagingConfiguration(Resource):
    """A Packaging Configuration for MediaPackage.

    See Also:
        `AWS Cloud Formation documentation for PackagingConfiguration
        <http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-mediapackage-packagingconfiguration.html>`_
    """

    RESOURCE_TYPE = "AWS::MediaPackage::PackagingConfiguration"

    Properties: PackagingConfigurationProperties = attrib(
        factory=PackagingConfigurationProperties,
        converter=create_object_converter(PackagingConfigurationProperties),
    )


@attrs(**ATTRSCONFIG)
class PackagingGroupProperties(ResourceProperties):
    Authorization = attrib(default=None)
    Id = attrib(default=None)
    Tags = attrib(default=None)


@attrs(**ATTRSCONFIG)
class PackagingGroup(Resource):
    """A Packaging Group for MediaPackage.

    See Also:
        `AWS Cloud Formation documentation for PackagingGroup
        <http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-mediapackage-packaginggroup.html>`_
    """

    RESOURCE_TYPE = "AWS::MediaPackage::PackagingGroup"

    Properties: PackagingGroupProperties = attrib(
        factory=PackagingGroupProperties,
        converter=create_object_converter(PackagingGroupProperties),
    )
