"""Raw representations of every data type in the AWS Timestream service.

See Also:
    `AWS developer guide for Timestream
    <https://docs.aws.amazon.com/timestream/latest/developerguide/what-is-timestream.html>`_

This file is automatically generated, and should not be directly edited.
"""

from attr import attrib
from attr import attrs

from ..core import ATTRSCONFIG
from ..core import Resource
from ..core import ResourceProperties
from ..core import create_object_converter

__all__ = ["Database", "DatabaseProperties", "Table", "TableProperties"]


@attrs(**ATTRSCONFIG)
class DatabaseProperties(ResourceProperties):
    DatabaseName = attrib(default=None)
    KmsKeyId = attrib(default=None)
    Tags = attrib(default=None)


@attrs(**ATTRSCONFIG)
class Database(Resource):
    """A Database for Timestream.

    See Also:
        `AWS Cloud Formation documentation for Database
        <http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-timestream-database.html>`_
    """

    RESOURCE_TYPE = "AWS::Timestream::Database"

    Properties: DatabaseProperties = attrib(
        factory=DatabaseProperties,
        converter=create_object_converter(DatabaseProperties),
    )


@attrs(**ATTRSCONFIG)
class TableProperties(ResourceProperties):
    DatabaseName = attrib(default=None)
    RetentionProperties = attrib(default=None)
    TableName = attrib(default=None)
    Tags = attrib(default=None)


@attrs(**ATTRSCONFIG)
class Table(Resource):
    """A Table for Timestream.

    See Also:
        `AWS Cloud Formation documentation for Table
        <http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-timestream-table.html>`_
    """

    RESOURCE_TYPE = "AWS::Timestream::Table"

    Properties: TableProperties = attrib(
        factory=TableProperties, converter=create_object_converter(TableProperties)
    )
